# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigationLines', '0002_investigationlines_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationlines',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='investigationlines',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
