# Generated by Django 2.1.1 on 2018-10-02 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('surnames', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('workDepartment', models.CharField(max_length=100)),
                ('academicTitle', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='investigator/')),
                ('active', models.BooleanField(default=1)),
                ('presentation', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investigator',
            },
        ),
    ]
