# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0005_investigator_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='telefono',
            field=models.CharField(max_length=25),
        ),
    ]
