# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0006_auto_20160508_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
    ]
