# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0007_auto_20160515_0909'),
        ('investigator', '0007_auto_20160508_2019'),
    ]

    operations = [
    ]
