# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='presentacion',
            field=models.CharField(default='Nada', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigator',
            name='titulo',
            field=models.CharField(default='Nada', max_length=100),
            preserve_default=False,
        ),
    ]
