# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0010_investigator_idcuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='idCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
