# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0012_investigator_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigator.Investigator')),
            ],
            options={
                'db_table': 'investigator_social',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_fa_class', models.CharField(max_length=100, null=True)),
                ('base_link', models.TextField()),
            ],
            options={
                'db_table': 'sociallinks',
            },
        ),
        migrations.AddField(
            model_name='investigator_social',
            name='social_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigator.SocialLinks'),
        ),
    ]
