# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0014_investigator_social_profile_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator_social',
            name='profile_social',
            field=models.TextField(),
        ),
    ]
