# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0015_auto_20160909_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigator_social',
            old_name='investigator_id',
            new_name='investigator',
        ),
        migrations.RenameField(
            model_name='investigator_social',
            old_name='social_id',
            new_name='social',
        ),
    ]
