# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0017_auto_20170423_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator_social',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='investigator_social',
            name='social',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='departamento',
            new_name='academicTitle',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='activo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='fechaNac',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='apellidos',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='fotoPerfil',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='presentacion',
            new_name='presentation',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='nombres',
            new_name='surnames',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='idCuenta',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='titulo',
            new_name='workDepartment',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='googlePlus',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='twitter',
        ),
        migrations.DeleteModel(
            name='Investigator_Social',
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
