# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='name',
        ),
    ]
