# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-06 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulescooperation',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='modulescooperation',
            name='master',
        ),
        migrations.DeleteModel(
            name='ModulesCooperation',
        ),
    ]
