# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0004_auto_20160706_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
