# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0005_auto_20160706_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
