# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0008_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
