# Generated by Django 2.1.1 on 2018-10-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('expression', models.CharField(max_length=50)),
                ('testimony', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('googlePlus', models.CharField(max_length=100, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='testimony/')),
                ('active', models.BooleanField(default=1)),
                ('privacy', models.BooleanField(default=1)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'testimony',
            },
        ),
    ]
