# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-07 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testimony',
            table='testimony',
        ),
    ]
