# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0002_auto_20160507_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 5, 8, 1, 37, 22, 77000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
