# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160617_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
    ]
