# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='owner',
        ),
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2016, 7, 31)),
            preserve_default=False,
        ),
    ]
