# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
            preserve_default=False,
        ),
    ]
