# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
