# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160801_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
