# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
