# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.TextField(default=''),
        ),
    ]
