# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.TextField(default='', null=True),
        ),
    ]
