# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigator', '0012_investigator_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('fechaDefensa', models.DateField()),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tesisgrade/')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigator.Investigator')),
            ],
            options={
                'db_table': 'tesisgrade',
            },
        ),
        migrations.CreateModel(
            name='PosGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('fechaDefensa', models.DateField()),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tesisposgrade/')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigator.Investigator')),
            ],
            options={
                'db_table': 'tesisposgrade',
            },
        ),
    ]
