# Generated by Django 2.1.1 on 2018-10-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vission', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('introductoryText', models.TextField(blank=True, null=True)),
                ('introductoryImage', models.FileField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
