# Generated by Django 2.1.1 on 2018-09-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='introductoryImage',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='introductoryText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
